### PR TITLE
fix(eslint): config will not use eslintrc from this project

### LINKED ISSUE #2: Example not work
I try run example
```
const format = require('prettier-eslint')

// notice, no semicolon in the original text
const sourceCode = 'const {foo} = bar'

const options = {
  text: sourceCode,
  eslintConfig: {
    rules: {
      semi: ['error', 'never'],
    },
  },
  prettierOptions: {
    bracketSpacing: true,
  },
}

const formatted = format(options)

// notice no semicolon in the formatted text
console.log(formatted) // const { foo } = bar
```
and output "undefined"

### PR DESCRIPTION
**Pull request by kentcdodds**
There was a problem with the way that eslint fix was applied which
basically resulted in test files in this project inheriting from the
`eslintConfig` from _this project_ (`prettier-eslint`). So I added
`useEslintrc: false` to the config which I believe will fix the issue
(can be overridden)

Also added a test for the README example so this doesn't happen again!

Could I get a review from @exdeniz and @demoneaux (and anyone else interested? ping @gyandeeps?)

Closes #2

### CODE REVIEW

File: src/__mocks__/eslint.js [hunk 1]
```diff
@@ -35,6 +35,7 @@ function mockGetConfigForFile(filePath) {
   return {
     '/mock/default-config': {
       rules: {
+        semi: [2, 'never'],
```
Comment (kentcdodds) [inline src/__mocks__/eslint.js]: Before this PR, this was actually inherited via the configuration from this project.

File: README.md [hunk 2]
```diff
@@ -54,6 +54,9 @@ const sourceCode = 'const {foo} = bar'
 const options = {
   text: sourceCode,
   eslintConfig: {
+    parserOptions: {
+      ecmaVersion: 7,
```
Comment (kentcdodds) [inline README.md]: This is the reason that you got `undefined` back. Because ESLint actually failed to parse the code (because it used `const`).

File: src/index.js [hunk 3]
```diff
@@ -35,7 +35,8 @@ function format({
 
   try {
     const pretty = prettify(text, prettierOptions)
-    return eslintFix(pretty, eslintConfig)
+    const eslintFixed = eslintFix(pretty, eslintConfig)
+    return eslintFixed
```
Comment (kentcdodds) [inline src/index.js]: Made this a variable name just so I can log it easier. Thinking that it could be useful to expose better logging control to log what the text is (if you want a silly amount of logs for example).

Comment (kentcdodds) [inline src/index.js]: But we'll do that later :)

File: src/index.js [hunk 4]
```diff
@@ -53,7 +54,13 @@ function prettify(text, formatOptions) {
 
 function eslintFix(text, eslintConfig) {
   const eslintOptions = {
+    // overrideables
+    useEslintrc: false,
```
Comment (kentcdodds) [inline src/index.js]: This can be overridden. I don't think that it's advisable to do though or whether this would even be something you'd need to do. But I thought it'd be good to expose a way to override it.

File: src/index.test.js [hunk 5]
```diff
@@ -16,6 +16,24 @@ const tests = [
     output: defaultOutput(),
   },
   {
+    title: 'README example',
```
Comment (kentcdodds) [inline src/index.test.js]: Added this so we don't have trouble in the future :)

**Comment by gyandeeps** [comment]
LGTM :+1:

File: src/index.js (hunk 4 above)
Comment (gyandeeps) [inline src/index.js]: I think would want to override this so that eslint can use their local `.eslintrc` files. Am i missing something here?

Comment (kentcdodds) [inline src/index.js]: Yeah, I think that makes sense. Normally, I expect people to simply pass the `filePath` and we'll get the `eslintConfig` from that (see `getConfig` [below](https://github.com/kentcdodds/prettier-eslint/blob/master/src/index.js#L79)). But if people are providing some special config in addition to what ESLint can find with the `.eslintrc` then that makes sense :)

File: .all-contributorsrc [hunk 6]
```diff
@@ -18,6 +18,15 @@
         "infra",
         "test"
       ]
+    },
+    {
+      "login": "gyandeeps",
```
Comment (kentcdodds) [inline .all-contributorsrc]: Is it ok if I add you as a contributor @gyandeeps? See [this](https://github.com/kentcdodds/prettier-eslint/blob/32c2002de7eab58047226e80b55ade257ebfdcb1/README.md#contributors) for what it'll look like.

File: .all-contributorsrc [hunk 7]
```diff
@@ -18,6 +18,33 @@
...
+      "name": "Gyandeep Singh",
+      "avatar_url": "https://avatars.githubusercontent.com/u/5554486?v=3",
+      "profile": "http://gyandeeps.com",
+      "contributions": [
+        "review"
+      ]
+    },
+    {
+      "login": "exdeniz",
```
Comment (kentcdodds) [inline .all-contributorsrc]: @exdeniz, are you ok with me adding you to the contributors list? See [this](https://github.com/kentcdodds/prettier-eslint/blob/e8518fc647c6374ceeddea7452f0cb23a25eece5/README.md#contributors) for what it will look like.

File: .all-contributorsrc [hunk 8]
```diff
@@ -18,6 +18,33 @@
...
+      "name": "Igor Pnev",
+      "avatar_url": "https://avatars.githubusercontent.com/u/682584?v=3",
+      "profile": "https://github.com/exdeniz",
+      "contributions": [
+        "bug"
+      ]
+    },
+    {
+      "login": "demoneaux",
```
Comment (kentcdodds) [inline .all-contributorsrc]: @ demoneaux, are you ok with me adding you to the contributors list? See [this](https://github.com/kentcdodds/prettier-eslint/blob/e8518fc647c6374ceeddea7452f0cb23a25eece5/README.md#contributors) for what it will look like.

Comment (kentcdodds) [inline .all-contributorsrc]: @demoneaux, are you ok with me adding you to the contributors list? See [this](https://github.com/kentcdodds/prettier-eslint/blob/e8518fc647c6374ceeddea7452f0cb23a25eece5/README.md#contributors) for what it will look like.

**Comment by kentcdodds** [comment]
@exdeniz and @demoneaux, I'm going to go ahead and merge this. If you'd like to remove yourself from `.all-contributorsrc` go ahead and let me know (or make a PR yourself). Thanks for your contribution!

File: .all-contributorsrc (hunk 7 above)
Comment (exdeniz) [inline .all-contributorsrc]: yes/
